"""Planned Iceberg table identifier contracts for the lean refoundation."""

RAW_NAMESPACE = "raw"
REF_NAMESPACE = "ref"
OPS_NAMESPACE = "ops"
INTERMEDIATE_NAMESPACE = "intermediate"
MART_NAMESPACE = "mart"

RAW_FULL_RESPONSES = f"{RAW_NAMESPACE}.full_responses"
RAW_BACKDATA = f"{RAW_NAMESPACE}.backdata"
RAW_MANUAL_OUTLIERS = f"{RAW_NAMESPACE}.manual_outliers"
RAW_MANUAL_TRIMMING = f"{RAW_NAMESPACE}.manual_trimming"

REF_ULTFOC_MAPPER = f"{REF_NAMESPACE}.ultfoc_mapper"
REF_POSTCODE_MAPPER = f"{REF_NAMESPACE}.postcode_mapper"
REF_PG_DETAILED_MAPPER = f"{REF_NAMESPACE}.pg_detailed_mapper"
REF_SIC_DIVISION_DETAILED_MAPPER = f"{REF_NAMESPACE}.sic_division_detailed_mapper"

OPS_RESPONSE_CORRECTIONS = f"{OPS_NAMESPACE}.response_corrections"
OPS_POSTCODE_CORRECTIONS = f"{OPS_NAMESPACE}.postcode_corrections"

INTERMEDIATE_STAGED_RESPONSES = f"{INTERMEDIATE_NAMESPACE}.staged_responses"
INTERMEDIATE_MAPPED_RESPONSES = f"{INTERMEDIATE_NAMESPACE}.mapped_responses"
INTERMEDIATE_IMPUTED_RESPONSES = f"{INTERMEDIATE_NAMESPACE}.imputed_responses"
INTERMEDIATE_OUTLIER_ADJUSTED_RESPONSES = (
    f"{INTERMEDIATE_NAMESPACE}.outlier_adjusted_responses"
)
INTERMEDIATE_ESTIMATED_RESPONSES = f"{INTERMEDIATE_NAMESPACE}.estimated_responses"
INTERMEDIATE_SITE_APPORTIONED_RESPONSES = (
    f"{INTERMEDIATE_NAMESPACE}.site_apportioned_responses"
)

MART_SHORT_FORM = f"{MART_NAMESPACE}.short_form"
MART_LONG_FORM = f"{MART_NAMESPACE}.long_form"
MART_INTRAM_TOTALS = f"{MART_NAMESPACE}.intram_totals"

PLANNED_TABLE_IDENTIFIERS = {
    RAW_FULL_RESPONSES,
    RAW_BACKDATA,
    RAW_MANUAL_OUTLIERS,
    RAW_MANUAL_TRIMMING,
    REF_ULTFOC_MAPPER,
    REF_POSTCODE_MAPPER,
    REF_PG_DETAILED_MAPPER,
    REF_SIC_DIVISION_DETAILED_MAPPER,
    OPS_RESPONSE_CORRECTIONS,
    OPS_POSTCODE_CORRECTIONS,
    INTERMEDIATE_STAGED_RESPONSES,
    INTERMEDIATE_MAPPED_RESPONSES,
    INTERMEDIATE_IMPUTED_RESPONSES,
    INTERMEDIATE_OUTLIER_ADJUSTED_RESPONSES,
    INTERMEDIATE_ESTIMATED_RESPONSES,
    INTERMEDIATE_SITE_APPORTIONED_RESPONSES,
    MART_SHORT_FORM,
    MART_LONG_FORM,
    MART_INTRAM_TOTALS,
}
